// Mocks generated by Mockito 5.4.6 from annotations
// in nook/test/features/crawl/presentation/bloc/crawl_claim_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nook/core/errors/failure.dart' as _i7;
import 'package:nook/core/services/gps_service.dart' as _i4;
import 'package:nook/features/crawl/domain/entities/stamp_claim_result.dart'
    as _i8;
import 'package:nook/features/crawl/domain/repositories/i_crawl_repository.dart'
    as _i2;
import 'package:nook/features/crawl/domain/use_cases/claim_stamp_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeICrawlRepository_0 extends _i1.SmartFake
    implements _i2.ICrawlRepository {
  _FakeICrawlRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGpsResult_2 extends _i1.SmartFake implements _i4.GpsResult {
  _FakeGpsResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClaimStampUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClaimStampUseCase extends _i1.Mock implements _i5.ClaimStampUseCase {
  @override
  _i2.ICrawlRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeICrawlRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeICrawlRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ICrawlRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.StampClaimResult>> call({
    required String? crawlId,
    required String? stopId,
    required double? lat,
    required double? lng,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #crawlId: crawlId,
              #stopId: stopId,
              #lat: lat,
              #lng: lng,
            }),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.StampClaimResult>>.value(
                  _FakeEither_1<_i7.Failure, _i8.StampClaimResult>(
                    this,
                    Invocation.method(#call, [], {
                      #crawlId: crawlId,
                      #stopId: stopId,
                      #lat: lat,
                      #lng: lng,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i3.Either<_i7.Failure, _i8.StampClaimResult>>.value(
                  _FakeEither_1<_i7.Failure, _i8.StampClaimResult>(
                    this,
                    Invocation.method(#call, [], {
                      #crawlId: crawlId,
                      #stopId: stopId,
                      #lat: lat,
                      #lng: lng,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.StampClaimResult>>);
}

/// A class which mocks [GpsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsService extends _i1.Mock implements _i4.GpsService {
  @override
  _i6.Future<_i4.GpsResult> getCurrentPosition({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, [], {#timeout: timeout}),
            returnValue: _i6.Future<_i4.GpsResult>.value(
              _FakeGpsResult_2(
                this,
                Invocation.method(#getCurrentPosition, [], {#timeout: timeout}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.GpsResult>.value(
              _FakeGpsResult_2(
                this,
                Invocation.method(#getCurrentPosition, [], {#timeout: timeout}),
              ),
            ),
          )
          as _i6.Future<_i4.GpsResult>);

  @override
  _i6.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isLocationEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
